const test = require('tape')
const checker = require('../')

test('decimal() tests', t => {
  t.plan(17)

  t.ok(checker.decimal(0.637), 'decimal(0.637) should be ok')
  t.ok(checker.decimal(-19.540), 'decimal(-19.540) should be ok')
  t.ok(checker.decimal(900000.00001), 'decimal(900000.00001) should be ok')
  t.ok(checker.decimal('1009.0055'), 'decimal(\'1009.0055\') should be ok')
  t.notOk(checker.decimal(-1), 'decimal(-1) should be falsy')
  t.notOk(checker.decimal(+1), 'decimal(+1) should be falsy')
  t.notOk(checker.decimal('0'), 'decimal(\'0\') should be falsy')
  t.notOk(checker.decimal(0), 'decimal(0) should be falsy')
  t.notOk(checker.decimal(null), 'decimal(null) should be falsy')
  t.notOk(checker.decimal(false), 'decimal(false) should be falsy')
  t.notOk(checker.decimal(true), 'decimal(true) should be falsy')
  t.notOk(checker.decimal(), 'decimal() should be falsy')
  t.notOk(checker.decimal(''), 'decimal(\'\') should be falsy')
  t.notOk(checker.decimal('abc'), 'decimal(\'abc\') should be falsy')
  t.notOk(checker.decimal([]), 'decimal([]) should be falsy')
  t.notOk(checker.decimal({}), 'decimal({}) should be falsy')
  t.notOk(checker.decimal('\n\r\t'), 'decimal(\'\n\r\t\') should be falsy')
})
